version: '3.2'

services:
  ift-4001-tp2:
    build: .
    tty: True
    volumes:
      - .:/app
    env_file:
      - ./env_files/.env

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data